# Generated by Django 4.0.3 on 2022-08-20 21:36

import apps.editor_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('position', models.IntegerField(verbose_name='Position')),
                ('type', models.CharField(choices=[('canvas', 'canvas'), ('text', 'text'), ('image', 'image')], default=apps.editor_app.models.PositionTypes['CANVAS'], max_length=250)),
                ('styles', models.JSONField(verbose_name='Styles')),
                ('parent_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor_app.element')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_edit', models.DateTimeField(auto_now=True, verbose_name='Last edit')),
            ],
        ),
        migrations.CreateModel(
            name='ElementTemplate',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor_app.element')),
            ],
        ),
    ]
