# Generated by Django 4.0.3 on 2022-08-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0004_item_remove_elementtemplate_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='Title'),
        ),
    ]
