# Generated by Django 4.0.3 on 2022-08-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor_app', '0005_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='position',
            field=models.PositiveIntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_list',
            field=models.ManyToManyField(null=True, to='editor_app.project', verbose_name='Item list'),
        ),
    ]
